### ISSUE TITLE
Support wss

### ISSUE THREAD

**Issue by arjunmenon** [Pithikos/python-websocket-server#48] opened 2018-05-12 19:41 UTC
Hey
I understand this lib at the moment doesn't support SSL but if we have to add the secure websocket, what can we do?

**Comment by Pithikos** [comment] 2018-06-14 07:44
This is duplicate of this: https://github.com/Pithikos/python-websocket-server/issues/35

I haven't dug much into it but I assume the main change would be replacing the HttpServer with an HttpsServer (if that exists).

**Closed** 2018-06-14 07:45 UTC
Labels: feature

**Comment by vmandke** [comment] 2018-12-14 12:57
class WebsocketServerSSL(WebsocketServer):
        def __init__(self, port, host='127.0.0.1', loglevel=logging.INFO):
            WebsocketServer.__init__(self, port, host, loglevel)
            self.context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
            self.context.load_cert_chain(cert_, privkey_)
            self.socket = self.context.wrap_socket(self.socket, server_side=True)

This works for me without any modifications to the lib

**Comment by HaukWong** [comment] 2019-07-02 09:16
> ```
> class WebsocketServerSSL(WebsocketServer):
>     def __init__(self, port, host='127.0.0.1', loglevel=logging.INFO):
>         WebsocketServer.__init__(self, port, host, loglevel)
>         self.context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
>         self.context.load_cert_chain(cert_, privkey_)
>         self.socket = self.context.wrap_socket(self.socket, server_side=True)
> ```
> 
> This works for me without any modifications to the lib

Does that mean you have achieved it?
